package arcade.cs622;

import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;


public class PongBoardRender extends JPanel

//used to paint components generated by other classes
{
	@Override
	protected void paintComponent(Graphics g)
	{
		super.paintComponent(g);

		PongGameLogic.pong.render((Graphics2D) g);
	}

}
// end PongBoardRender
